# Generated by Django 3.1.12 on 2023-02-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_requirements_what_will_you_learn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Requirement',
        ),
    ]
